name: shop_navigator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/logos/
    - assets/imgs/products/
    - assets/imgs/vectors/
    - assets/imgs/banners/
    - assets/icons/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSans(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans(FaNum)_Bold.ttf
          weight: 600
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
          weight: 400
